### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by santokhsingh** [Netflix/Raigad#6]
Running into build issues with Raigad. Build fails while executing test cases present in TestElasticsearchConfig. Does your test cases require Cassandra host to be up at the time of build? I am running elasticsearch 1.4 on ubuntu.

Here is the stack trace>>

com.netflix.raigad.resources.TestElasticsearchConfig > getNodes_handlesUnknownHostException FAILED
    java.lang.IllegalStateException at TestElasticsearchConfig.java:80

31 tests completed, 1 failed
:raigad:test FAILED

FAILURE: Build failed with an exception.

**Comment by sagarl** [comment]
@santokhsingh , I have updated the Wiki (Setup page) with updated information and also added new Configuration Properties page. Let me know if this helps.

Thanks,
Sagar
