### ISSUE TITLE
Compatibility with ES5 and non AWS Clusters

### ISSUE THREAD

**Issue by mathewmeconry** [Netflix/Raigad#87]
Hi

I found in the [wiki](https://github.com/Netflix/Raigad/wiki/Compatibility) that Raigad does only support ES 1.5.2. Are there any plans to support newer versions?

And does it work with clusters which aren't hosted on AWS too. I'm looking for the functionalities "backup and restore" , "Automated Index Management" and "monitoring"

Thanks for your help

**Comment by gndcshv** [comment]
Hi @mathewmeconry, I have updated the Wiki page you referenced - master branch currently supports Elasticsearch version `2.4.1`. We are working on rolling out support for ES 5.x too.

**Comment by mathewmeconry** [comment]
Hi @gndcshv thanks

**Comment by cpeeyush** [comment]
@gndcshv  Any idea till what time ES 5.x will be supported?
